import '../models/game_profile.dart';

class GameData {
  static const List<GameProfile> defaultCatalog = [
    // ----------------- COMPETITIVE & MATCH-BASED -----------------
    GameProfile(
      id: 'valorant',
      name: 'Valorant',
      category: GameCategory.competitive,
      iconName: 'valorant',
      color: 0xFFFF4655,
      modes: [
        GameMode(
          name: 'Competitive',
          estimatedMinutes: 40,
          minMinutes: 30,
          maxMinutes: 50,
          commitmentType: GameCommitmentType.commitment,
          canLeaveSafely: false,
          isCompetitive: true,
        ),
        GameMode(
          name: 'Unrated',
          estimatedMinutes: 35,
          minMinutes: 25,
          maxMinutes: 45,
          commitmentType: GameCommitmentType.commitment,
          canLeaveSafely: false,
          isCompetitive: false,
        ),
        GameMode(
          name: 'Swiftplay',
          estimatedMinutes: 15,
          minMinutes: 10,
          maxMinutes: 18,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: false,
          isCompetitive: false,
        ),
        GameMode(
          name: 'Deathmatch',
          estimatedMinutes: 10,
          minMinutes: 8,
          maxMinutes: 12,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: true,
          isCompetitive: false,
        ),
        GameMode(
          name: 'Spike Rush',
          estimatedMinutes: 8,
          minMinutes: 6,
          maxMinutes: 12,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: false,
          isCompetitive: false,
        ),
      ],
    ),
    GameProfile(
      id: 'league_of_legends',
      name: 'League of Legends',
      category: GameCategory.competitive,
      iconName: 'league',
      color: 0xFFC89B3C,
      modes: [
        GameMode(
          name: 'Ranked Solo/Duo',
          estimatedMinutes: 35,
          minMinutes: 25,
          maxMinutes: 48,
          commitmentType: GameCommitmentType.commitment,
          canLeaveSafely: false,
          isCompetitive: true,
        ),
        GameMode(
          name: 'Normal Summoner\'s Rift',
          estimatedMinutes: 30,
          minMinutes: 22,
          maxMinutes: 42,
          commitmentType: GameCommitmentType.commitment,
          canLeaveSafely: false,
          isCompetitive: false,
        ),
        GameMode(
          name: 'ARAM',
          estimatedMinutes: 20,
          minMinutes: 14,
          maxMinutes: 28,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: false,
          isCompetitive: false,
        ),
        GameMode(
          name: 'Arena 2v2v2v2',
          estimatedMinutes: 15,
          minMinutes: 10,
          maxMinutes: 20,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: false,
          isCompetitive: true,
        ),
      ],
    ),
    GameProfile(
      id: 'cs2',
      name: 'Counter-Strike 2',
      category: GameCategory.competitive,
      iconName: 'cs2',
      color: 0xFFDE9B35,
      modes: [
        GameMode(
          name: 'Premier / Competitive',
          estimatedMinutes: 40,
          minMinutes: 28,
          maxMinutes: 52,
          commitmentType: GameCommitmentType.commitment,
          canLeaveSafely: false,
          isCompetitive: true,
        ),
        GameMode(
          name: 'Casual',
          estimatedMinutes: 25,
          minMinutes: 15,
          maxMinutes: 30,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: true,
          isCompetitive: false,
        ),
        GameMode(
          name: 'Deathmatch',
          estimatedMinutes: 10,
          minMinutes: 8,
          maxMinutes: 10,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: true,
          isCompetitive: false,
        ),
        GameMode(
          name: 'Arms Race',
          estimatedMinutes: 10,
          minMinutes: 6,
          maxMinutes: 12,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: true,
          isCompetitive: false,
        ),
      ],
    ),
    GameProfile(
      id: 'dota2',
      name: 'Dota 2',
      category: GameCategory.competitive,
      iconName: 'dota',
      color: 0xFFBE1E2D,
      modes: [
        GameMode(
          name: 'Ranked All Pick',
          estimatedMinutes: 45,
          minMinutes: 30,
          maxMinutes: 65,
          commitmentType: GameCommitmentType.commitment,
          canLeaveSafely: false,
          isCompetitive: true,
        ),
        GameMode(
          name: 'Turbo Mode',
          estimatedMinutes: 25,
          minMinutes: 18,
          maxMinutes: 35,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: false,
          isCompetitive: false,
        ),
        GameMode(
          name: 'Ability Draft',
          estimatedMinutes: 35,
          minMinutes: 25,
          maxMinutes: 50,
          commitmentType: GameCommitmentType.commitment,
          canLeaveSafely: false,
          isCompetitive: false,
        ),
      ],
    ),
    GameProfile(
      id: 'overwatch2',
      name: 'Overwatch 2',
      category: GameCategory.competitive,
      iconName: 'overwatch',
      color: 0xFFF99E1A,
      modes: [
        GameMode(
          name: 'Competitive',
          estimatedMinutes: 25,
          minMinutes: 18,
          maxMinutes: 35,
          commitmentType: GameCommitmentType.commitment,
          canLeaveSafely: false,
          isCompetitive: true,
        ),
        GameMode(
          name: 'Quick Play',
          estimatedMinutes: 15,
          minMinutes: 10,
          maxMinutes: 20,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: true,
          isCompetitive: false,
        ),
        GameMode(
          name: 'Arcade / Mystery Heroes',
          estimatedMinutes: 12,
          minMinutes: 8,
          maxMinutes: 16,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: true,
          isCompetitive: false,
        ),
      ],
    ),
    GameProfile(
      id: 'fortnite',
      name: 'Fortnite',
      category: GameCategory.competitive,
      iconName: 'fortnite',
      color: 0xFF00D4FF,
      modes: [
        GameMode(
          name: 'Ranked Battle Royale',
          estimatedMinutes: 25,
          minMinutes: 15,
          maxMinutes: 30,
          commitmentType: GameCommitmentType.commitment,
          canLeaveSafely: false,
          isCompetitive: true,
        ),
        GameMode(
          name: 'Zero Build',
          estimatedMinutes: 22,
          minMinutes: 12,
          maxMinutes: 28,
          commitmentType: GameCommitmentType.commitment,
          canLeaveSafely: false,
          isCompetitive: false,
        ),
        GameMode(
          name: 'Creative & Zone Wars',
          estimatedMinutes: 15,
          minMinutes: 8,
          maxMinutes: 20,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: true,
          isCompetitive: false,
        ),
      ],
    ),
    GameProfile(
      id: 'apex_legends',
      name: 'Apex Legends',
      category: GameCategory.competitive,
      iconName: 'apex',
      color: 0xFFDA292A,
      modes: [
        GameMode(
          name: 'Ranked Leagues',
          estimatedMinutes: 22,
          minMinutes: 14,
          maxMinutes: 28,
          commitmentType: GameCommitmentType.commitment,
          canLeaveSafely: false,
          isCompetitive: true,
        ),
        GameMode(
          name: 'Trios / Duos',
          estimatedMinutes: 18,
          minMinutes: 10,
          maxMinutes: 25,
          commitmentType: GameCommitmentType.commitment,
          canLeaveSafely: false,
          isCompetitive: false,
        ),
        GameMode(
          name: 'Mixtape (Control / Gun Run)',
          estimatedMinutes: 12,
          minMinutes: 8,
          maxMinutes: 15,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: true,
          isCompetitive: false,
        ),
      ],
    ),
    GameProfile(
      id: 'rocket_league',
      name: 'Rocket League',
      category: GameCategory.competitive,
      iconName: 'rocket',
      color: 0xFF0079FF,
      modes: [
        GameMode(
          name: 'Competitive (2v2 / 3v3)',
          estimatedMinutes: 8,
          minMinutes: 6,
          maxMinutes: 12,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: false,
          isCompetitive: true,
        ),
        GameMode(
          name: 'Casual Matches',
          estimatedMinutes: 7,
          minMinutes: 5,
          maxMinutes: 10,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: true,
          isCompetitive: false,
        ),
        GameMode(
          name: 'Extra Modes (Rumble / Hoops)',
          estimatedMinutes: 7,
          minMinutes: 5,
          maxMinutes: 10,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: true,
          isCompetitive: false,
        ),
      ],
    ),
    GameProfile(
      id: 'r6_siege',
      name: 'Rainbow Six Siege',
      category: GameCategory.competitive,
      iconName: 'r6',
      color: 0xFF2D55FF,
      modes: [
        GameMode(
          name: 'Ranked',
          estimatedMinutes: 35,
          minMinutes: 25,
          maxMinutes: 45,
          commitmentType: GameCommitmentType.commitment,
          canLeaveSafely: false,
          isCompetitive: true,
        ),
        GameMode(
          name: 'Standard / Unranked',
          estimatedMinutes: 28,
          minMinutes: 18,
          maxMinutes: 38,
          commitmentType: GameCommitmentType.commitment,
          canLeaveSafely: false,
          isCompetitive: false,
        ),
        GameMode(
          name: 'Quick Match',
          estimatedMinutes: 15,
          minMinutes: 10,
          maxMinutes: 20,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: true,
          isCompetitive: false,
        ),
      ],
    ),
    GameProfile(
      id: 'warzone',
      name: 'Call of Duty: Warzone',
      category: GameCategory.competitive,
      iconName: 'warzone',
      color: 0xFF4CAF50,
      modes: [
        GameMode(
          name: 'Battle Royale (Trios/Quads)',
          estimatedMinutes: 28,
          minMinutes: 18,
          maxMinutes: 35,
          commitmentType: GameCommitmentType.commitment,
          canLeaveSafely: false,
          isCompetitive: true,
        ),
        GameMode(
          name: 'Resurgence',
          estimatedMinutes: 15,
          minMinutes: 10,
          maxMinutes: 20,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: false,
          isCompetitive: false,
        ),
        GameMode(
          name: 'Multiplayer TDM',
          estimatedMinutes: 10,
          minMinutes: 7,
          maxMinutes: 12,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: true,
          isCompetitive: false,
        ),
      ],
    ),
    GameProfile(
      id: 'fc24',
      name: 'EA SPORTS FC 24 / FIFA',
      category: GameCategory.competitive,
      iconName: 'fc24',
      color: 0xFF00FF85,
      modes: [
        GameMode(
          name: 'Ultimate Team Champions / Rivals',
          estimatedMinutes: 20,
          minMinutes: 15,
          maxMinutes: 25,
          commitmentType: GameCommitmentType.commitment,
          canLeaveSafely: false,
          isCompetitive: true,
        ),
        GameMode(
          name: 'Online Seasons / Kick-Off',
          estimatedMinutes: 15,
          minMinutes: 12,
          maxMinutes: 20,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: false,
          isCompetitive: false,
        ),
      ],
    ),
    GameProfile(
      id: 'mlbb',
      name: 'Mobile Legends: Bang Bang',
      category: GameCategory.competitive,
      iconName: 'mlbb',
      color: 0xFFF0C330,
      modes: [
        GameMode(
          name: 'Ranked Match',
          estimatedMinutes: 20,
          minMinutes: 14,
          maxMinutes: 28,
          commitmentType: GameCommitmentType.commitment,
          canLeaveSafely: false,
          isCompetitive: true,
        ),
        GameMode(
          name: 'Classic',
          estimatedMinutes: 16,
          minMinutes: 12,
          maxMinutes: 24,
          commitmentType: GameCommitmentType.commitment,
          canLeaveSafely: false,
          isCompetitive: false,
        ),
        GameMode(
          name: 'Brawl',
          estimatedMinutes: 8,
          minMinutes: 5,
          maxMinutes: 12,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: false,
          isCompetitive: false,
        ),
      ],
    ),
    GameProfile(
      id: 'pubg_mobile',
      name: 'PUBG Mobile',
      category: GameCategory.competitive,
      iconName: 'pubg',
      color: 0xFFF3A712,
      modes: [
        GameMode(
          name: 'Classic Erangel/Miramar',
          estimatedMinutes: 30,
          minMinutes: 18,
          maxMinutes: 35,
          commitmentType: GameCommitmentType.commitment,
          canLeaveSafely: false,
          isCompetitive: true,
        ),
        GameMode(
          name: 'Livik / Nusa Quick Map',
          estimatedMinutes: 15,
          minMinutes: 10,
          maxMinutes: 18,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: false,
          isCompetitive: false,
        ),
        GameMode(
          name: 'Arena TDM 4v4',
          estimatedMinutes: 8,
          minMinutes: 6,
          maxMinutes: 10,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: true,
          isCompetitive: false,
        ),
      ],
    ),

    // ----------------- CASUAL & FLEXIBLE GAMES -----------------
    GameProfile(
      id: 'minecraft',
      name: 'Minecraft',
      category: GameCategory.casual,
      iconName: 'minecraft',
      color: 0xFF5E9634,
      modes: [
        GameMode(
          name: 'Singleplayer Survival',
          estimatedMinutes: 30,
          commitmentType: GameCommitmentType.flexible,
          canLeaveSafely: true,
          isCompetitive: false,
        ),
        GameMode(
          name: 'Multiplayer Server SMP',
          estimatedMinutes: 30,
          commitmentType: GameCommitmentType.flexible,
          canLeaveSafely: true,
          isCompetitive: false,
        ),
        GameMode(
          name: 'Server Bedwars / Skywars',
          estimatedMinutes: 15,
          minMinutes: 8,
          maxMinutes: 20,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: false,
          isCompetitive: true,
        ),
      ],
    ),
    GameProfile(
      id: 'terraria',
      name: 'Terraria',
      category: GameCategory.casual,
      iconName: 'terraria',
      color: 0xFF35A753,
      modes: [
        GameMode(
          name: 'Adventure & Building',
          estimatedMinutes: 30,
          commitmentType: GameCommitmentType.flexible,
          canLeaveSafely: true,
          isCompetitive: false,
        ),
        GameMode(
          name: 'Boss Fight Progression',
          estimatedMinutes: 15,
          commitmentType: GameCommitmentType.flexible,
          canLeaveSafely: true,
          isCompetitive: false,
        ),
      ],
    ),
    GameProfile(
      id: 'stardew_valley',
      name: 'Stardew Valley',
      category: GameCategory.casual,
      iconName: 'stardew',
      color: 0xFFFF9800,
      modes: [
        GameMode(
          name: 'Daily In-Game Cycle',
          estimatedMinutes: 15,
          minMinutes: 12,
          maxMinutes: 16,
          commitmentType: GameCommitmentType.flexible,
          canLeaveSafely: true,
          isCompetitive: false,
        ),
      ],
    ),
    GameProfile(
      id: 'roblox',
      name: 'Roblox',
      category: GameCategory.casual,
      iconName: 'roblox',
      color: 0xFFE53935,
      modes: [
        GameMode(
          name: 'Casual Obby / Roleplay',
          estimatedMinutes: 15,
          commitmentType: GameCommitmentType.flexible,
          canLeaveSafely: true,
          isCompetitive: false,
        ),
        GameMode(
          name: 'Minigames / Rivals',
          estimatedMinutes: 10,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: true,
          isCompetitive: false,
        ),
      ],
    ),
    GameProfile(
      id: 'brawlstars',
      name: 'Brawl Stars',
      category: GameCategory.competitive,
      iconName: 'brawlstars',
      color: 0xFFFDC500,
      modes: [
        GameMode(
          name: 'Ranked Gem Grab / Brawl Ball',
          estimatedMinutes: 5,
          minMinutes: 3,
          maxMinutes: 8,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: false,
          isCompetitive: true,
        ),
        GameMode(
          name: 'Solo / Duo Showdown',
          estimatedMinutes: 4,
          minMinutes: 2,
          maxMinutes: 6,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: true,
          isCompetitive: false,
        ),
      ],
    ),
    GameProfile(
      id: 'clash_royale',
      name: 'Clash Royale',
      category: GameCategory.competitive,
      iconName: 'clash_royale',
      color: 0xFF1E88E5,
      modes: [
        GameMode(
          name: 'Trophy Road / Path of Legends',
          estimatedMinutes: 5,
          minMinutes: 3,
          maxMinutes: 6,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: false,
          isCompetitive: true,
        ),
        GameMode(
          name: '2v2 / Party Mode',
          estimatedMinutes: 4,
          minMinutes: 3,
          maxMinutes: 5,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: true,
          isCompetitive: false,
        ),
      ],
    ),
    GameProfile(
      id: 'clash_of_clans',
      name: 'Clash of Clans',
      category: GameCategory.casual,
      iconName: 'clash_of_clans',
      color: 0xFFFF9800,
      modes: [
        GameMode(
          name: 'Multiplayer Attack & Farming',
          estimatedMinutes: 4,
          minMinutes: 3,
          maxMinutes: 5,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: true,
          isCompetitive: false,
        ),
        GameMode(
          name: 'Clan War Attack',
          estimatedMinutes: 4,
          minMinutes: 3,
          maxMinutes: 4,
          commitmentType: GameCommitmentType.shortSession,
          canLeaveSafely: false,
          isCompetitive: true,
        ),
      ],
    ),
    GameProfile(
      id: 'genshin',
      name: 'Genshin Impact',
      category: GameCategory.casual,
      iconName: 'genshin',
      color: 0xFF48C5E2,
      modes: [
        GameMode(
          name: 'Daily Commissions & Resin Domains',
          estimatedMinutes: 15,
          minMinutes: 10,
          maxMinutes: 20,
          commitmentType: GameCommitmentType.flexible,
          canLeaveSafely: true,
          isCompetitive: false,
        ),
        GameMode(
          name: 'Spiral Abyss',
          estimatedMinutes: 20,
          minMinutes: 15,
          maxMinutes: 30,
          commitmentType: GameCommitmentType.commitment,
          canLeaveSafely: true,
          isCompetitive: true,
        ),
      ],
    ),
  ];
}

