import '../models/game_profile.dart';

class GameData {
  static const List<GameProfile> defaultCatalog = [
    // ----------------- COMPETITIVE & MATCH-BASED -----------------
    GameProfile(
      id: 'valorant',
      name: 'Valorant',
      category: GameCategory.competitive,
      iconName: 'valorant',
      color: 0xFFFF4655,
      activities: [
        GameActivity(
          id: 'val_ranked',
          gameId: 'valorant',
          name: 'Competitive / Ranked',
          typicalDuration: 40,
          minMinutes: 30,
          maxMinutes: 55,
          canPause: false,
          requiresCompletion: true,
          isCompetitive: true,
          commitmentType: GameCommitmentType.commitment,
        ),
        GameActivity(
          id: 'val_unrated',
          gameId: 'valorant',
          name: 'Unrated',
          typicalDuration: 35,
          minMinutes: 25,
          maxMinutes: 45,
          canPause: false,
          requiresCompletion: true,
          isCompetitive: false,
          commitmentType: GameCommitmentType.commitment,
        ),
        GameActivity(
          id: 'val_swiftplay',
          gameId: 'valorant',
          name: 'Swiftplay',
          typicalDuration: 15,
          minMinutes: 10,
          maxMinutes: 18,
          canPause: false,
          requiresCompletion: true,
          isCompetitive: false,
          commitmentType: GameCommitmentType.shortSession,
        ),
        GameActivity(
          id: 'val_deathmatch',
          gameId: 'valorant',
          name: 'Deathmatch',
          typicalDuration: 10,
          minMinutes: 8,
          maxMinutes: 12,
          canPause: true,
          requiresCompletion: false,
          isCompetitive: false,
          commitmentType: GameCommitmentType.shortSession,
        ),
        GameActivity(
          id: 'val_spike_rush',
          gameId: 'valorant',
          name: 'Spike Rush',
          typicalDuration: 8,
          minMinutes: 6,
          maxMinutes: 12,
          canPause: false,
          requiresCompletion: true,
          isCompetitive: false,
          commitmentType: GameCommitmentType.shortSession,
        ),
      ],
    ),
    GameProfile(
      id: 'league_of_legends',
      name: 'League of Legends',
      category: GameCategory.competitive,
      iconName: 'league',
      color: 0xFFC89B3C,
      activities: [
        GameActivity(
          id: 'lol_ranked',
          gameId: 'league_of_legends',
          name: 'Ranked Solo/Duo',
          typicalDuration: 35,
          minMinutes: 25,
          maxMinutes: 50,
          canPause: false,
          requiresCompletion: true,
          isCompetitive: true,
          commitmentType: GameCommitmentType.commitment,
        ),
        GameActivity(
          id: 'lol_normal',
          gameId: 'league_of_legends',
          name: 'Normal Summoner\'s Rift',
          typicalDuration: 30,
          minMinutes: 22,
          maxMinutes: 42,
          canPause: false,
          requiresCompletion: true,
          isCompetitive: false,
          commitmentType: GameCommitmentType.commitment,
        ),
        GameActivity(
          id: 'lol_aram',
          gameId: 'league_of_legends',
          name: 'ARAM (All Random All Mid)',
          typicalDuration: 20,
          minMinutes: 14,
          maxMinutes: 28,
          canPause: false,
          requiresCompletion: true,
          isCompetitive: false,
          commitmentType: GameCommitmentType.shortSession,
        ),
        GameActivity(
          id: 'lol_arena',
          gameId: 'league_of_legends',
          name: 'Arena 2v2v2v2',
          typicalDuration: 15,
          minMinutes: 10,
          maxMinutes: 22,
          canPause: false,
          requiresCompletion: true,
          isCompetitive: false,
          commitmentType: GameCommitmentType.shortSession,
        ),
      ],
    ),
    GameProfile(
      id: 'cs2',
      name: 'Counter-Strike 2',
      category: GameCategory.competitive,
      iconName: 'cs2',
      color: 0xFFDE9B35,
      activities: [
        GameActivity(
          id: 'cs2_premier',
          gameId: 'cs2',
          name: 'Premier / Competitive',
          typicalDuration: 40,
          minMinutes: 30,
          maxMinutes: 55,
          canPause: false,
          requiresCompletion: true,
          isCompetitive: true,
          commitmentType: GameCommitmentType.commitment,
        ),
        GameActivity(
          id: 'cs2_wingman',
          gameId: 'cs2',
          name: 'Wingman 2v2',
          typicalDuration: 15,
          minMinutes: 10,
          maxMinutes: 22,
          canPause: false,
          requiresCompletion: true,
          isCompetitive: true,
          commitmentType: GameCommitmentType.shortSession,
        ),
        GameActivity(
          id: 'cs2_deathmatch',
          gameId: 'cs2',
          name: 'Casual / Deathmatch',
          typicalDuration: 10,
          minMinutes: 5,
          maxMinutes: 15,
          canPause: true,
          requiresCompletion: false,
          isCompetitive: false,
          commitmentType: GameCommitmentType.shortSession,
        ),
      ],
    ),
    GameProfile(
      id: 'rocket_league',
      name: 'Rocket League',
      category: GameCategory.competitive,
      iconName: 'rocket_league',
      color: 0xFF0080FF,
      activities: [
        GameActivity(
          id: 'rl_ranked',
          gameId: 'rocket_league',
          name: 'Ranked 2v2 / 3v3',
          typicalDuration: 7,
          minMinutes: 5,
          maxMinutes: 10,
          canPause: false,
          requiresCompletion: true,
          isCompetitive: true,
          commitmentType: GameCommitmentType.shortSession,
        ),
        GameActivity(
          id: 'rl_tournament',
          gameId: 'rocket_league',
          name: 'Scheduled Tournament',
          typicalDuration: 35,
          minMinutes: 20,
          maxMinutes: 50,
          canPause: false,
          requiresCompletion: true,
          isCompetitive: true,
          commitmentType: GameCommitmentType.commitment,
        ),
        GameActivity(
          id: 'rl_casual',
          gameId: 'rocket_league',
          name: 'Casual & Extra Modes',
          typicalDuration: 6,
          minMinutes: 5,
          maxMinutes: 8,
          canPause: true,
          requiresCompletion: false,
          isCompetitive: false,
          commitmentType: GameCommitmentType.shortSession,
        ),
      ],
    ),
    GameProfile(
      id: 'fortnite',
      name: 'Fortnite',
      category: GameCategory.competitive,
      iconName: 'fortnite',
      color: 0xFF9C27B0,
      activities: [
        GameActivity(
          id: 'fn_br_ranked',
          gameId: 'fortnite',
          name: 'Battle Royale (Ranked)',
          typicalDuration: 22,
          minMinutes: 15,
          maxMinutes: 26,
          canPause: false,
          requiresCompletion: true,
          isCompetitive: true,
          commitmentType: GameCommitmentType.commitment,
        ),
        GameActivity(
          id: 'fn_br_casual',
          gameId: 'fortnite',
          name: 'Battle Royale / Zero Build',
          typicalDuration: 18,
          minMinutes: 10,
          maxMinutes: 24,
          canPause: false,
          requiresCompletion: false,
          isCompetitive: false,
          commitmentType: GameCommitmentType.shortSession,
        ),
        GameActivity(
          id: 'fn_creative',
          gameId: 'fortnite',
          name: 'Creative / Lego / Festival',
          typicalDuration: 20,
          minMinutes: 10,
          maxMinutes: 45,
          canPause: true,
          requiresCompletion: false,
          isCompetitive: false,
          commitmentType: GameCommitmentType.flexible,
        ),
      ],
    ),
    GameProfile(
      id: 'apex_legends',
      name: 'Apex Legends',
      category: GameCategory.competitive,
      iconName: 'apex',
      color: 0xFFDA292A,
      activities: [
        GameActivity(
          id: 'apex_ranked',
          gameId: 'apex_legends',
          name: 'Ranked Battle Royale',
          typicalDuration: 20,
          minMinutes: 12,
          maxMinutes: 25,
          canPause: false,
          requiresCompletion: true,
          isCompetitive: true,
          commitmentType: GameCommitmentType.commitment,
        ),
        GameActivity(
          id: 'apex_mixtape',
          gameId: 'apex_legends',
          name: 'Mixtape (Control / Gun Run / TDM)',
          typicalDuration: 12,
          minMinutes: 8,
          maxMinutes: 15,
          canPause: false,
          requiresCompletion: false,
          isCompetitive: false,
          commitmentType: GameCommitmentType.shortSession,
        ),
      ],
    ),
    GameProfile(
      id: 'overwatch2',
      name: 'Overwatch 2',
      category: GameCategory.competitive,
      iconName: 'overwatch',
      color: 0xFFF99E1A,
      activities: [
        GameActivity(
          id: 'ow2_comp',
          gameId: 'overwatch2',
          name: 'Competitive Role Queue',
          typicalDuration: 20,
          minMinutes: 14,
          maxMinutes: 28,
          canPause: false,
          requiresCompletion: true,
          isCompetitive: true,
          commitmentType: GameCommitmentType.commitment,
        ),
        GameActivity(
          id: 'ow2_quickplay',
          gameId: 'overwatch2',
          name: 'Quick Play / Arcade',
          typicalDuration: 10,
          minMinutes: 7,
          maxMinutes: 15,
          canPause: false,
          requiresCompletion: false,
          isCompetitive: false,
          commitmentType: GameCommitmentType.shortSession,
        ),
      ],
    ),
    GameProfile(
      id: 'dota2',
      name: 'Dota 2',
      category: GameCategory.competitive,
      iconName: 'dota2',
      color: 0xFFC23C2A,
      activities: [
        GameActivity(
          id: 'dota_ranked',
          gameId: 'dota2',
          name: 'Ranked All Pick',
          typicalDuration: 45,
          minMinutes: 30,
          maxMinutes: 65,
          canPause: false,
          requiresCompletion: true,
          isCompetitive: true,
          commitmentType: GameCommitmentType.commitment,
        ),
        GameActivity(
          id: 'dota_turbo',
          gameId: 'dota2',
          name: 'Turbo Mode',
          typicalDuration: 25,
          minMinutes: 18,
          maxMinutes: 35,
          canPause: false,
          requiresCompletion: true,
          isCompetitive: false,
          commitmentType: GameCommitmentType.shortSession,
        ),
      ],
    ),
    GameProfile(
      id: 'r6_siege',
      name: 'Rainbow Six Siege',
      category: GameCategory.competitive,
      iconName: 'r6',
      color: 0xFF2196F3,
      activities: [
        GameActivity(
          id: 'r6_ranked',
          gameId: 'r6_siege',
          name: 'Ranked / Standard',
          typicalDuration: 30,
          minMinutes: 20,
          maxMinutes: 40,
          canPause: false,
          requiresCompletion: true,
          isCompetitive: true,
          commitmentType: GameCommitmentType.commitment,
        ),
        GameActivity(
          id: 'r6_quick',
          gameId: 'r6_siege',
          name: 'Quick Match / Arcade',
          typicalDuration: 12,
          minMinutes: 8,
          maxMinutes: 18,
          canPause: false,
          requiresCompletion: false,
          isCompetitive: false,
          commitmentType: GameCommitmentType.shortSession,
        ),
      ],
    ),
    GameProfile(
      id: 'eafc',
      name: 'EA FC 25 / FIFA',
      category: GameCategory.competitive,
      iconName: 'fifa',
      color: 0xFF00E676,
      activities: [
        GameActivity(
          id: 'fc_rivals',
          gameId: 'eafc',
          name: 'Ultimate Team Champions / Rivals',
          typicalDuration: 18,
          minMinutes: 14,
          maxMinutes: 24,
          canPause: false,
          requiresCompletion: true,
          isCompetitive: true,
          commitmentType: GameCommitmentType.commitment,
        ),
        GameActivity(
          id: 'fc_career',
          gameId: 'eafc',
          name: 'Career Mode / Kick-Off',
          typicalDuration: 15,
          minMinutes: 10,
          maxMinutes: 20,
          canPause: true,
          requiresCompletion: false,
          isCompetitive: false,
          commitmentType: GameCommitmentType.flexible,
        ),
      ],
    ),
    GameProfile(
      id: 'cod_warzone',
      name: 'Call of Duty: Warzone',
      category: GameCategory.competitive,
      iconName: 'warzone',
      color: 0xFF78909C,
      activities: [
        GameActivity(
          id: 'wz_br',
          gameId: 'cod_warzone',
          name: 'Battle Royale Squads',
          typicalDuration: 25,
          minMinutes: 18,
          maxMinutes: 30,
          canPause: false,
          requiresCompletion: true,
          isCompetitive: true,
          commitmentType: GameCommitmentType.commitment,
        ),
        GameActivity(
          id: 'wz_resurgence',
          gameId: 'cod_warzone',
          name: 'Resurgence / Plunder',
          typicalDuration: 15,
          minMinutes: 10,
          maxMinutes: 20,
          canPause: false,
          requiresCompletion: false,
          isCompetitive: false,
          commitmentType: GameCommitmentType.shortSession,
        ),
      ],
    ),

    // ----------------- CASUAL, OPEN WORLD & FLEXIBLE -----------------
    GameProfile(
      id: 'minecraft',
      name: 'Minecraft',
      category: GameCategory.casual,
      iconName: 'minecraft',
      color: 0xFF5E9634,
      activities: [
        GameActivity(
          id: 'mc_survival',
          gameId: 'minecraft',
          name: 'Singleplayer Survival',
          typicalDuration: 45,
          minMinutes: 20,
          maxMinutes: 90,
          canPause: true,
          requiresCompletion: false,
          isCompetitive: false,
          commitmentType: GameCommitmentType.flexible,
        ),
        GameActivity(
          id: 'mc_hardcore',
          gameId: 'minecraft',
          name: 'Hardcore Survival',
          typicalDuration: 60,
          minMinutes: 30,
          maxMinutes: 120,
          canPause: true,
          requiresCompletion: false,
          isCompetitive: true,
          commitmentType: GameCommitmentType.flexible,
        ),
        GameActivity(
          id: 'mc_pvp',
          gameId: 'minecraft',
          name: 'Server PvP / Bedwars / Skywars',
          typicalDuration: 15,
          minMinutes: 8,
          maxMinutes: 22,
          canPause: false,
          requiresCompletion: true,
          isCompetitive: true,
          commitmentType: GameCommitmentType.shortSession,
        ),
        GameActivity(
          id: 'mc_creative',
          gameId: 'minecraft',
          name: 'Creative / Building',
          typicalDuration: 30,
          minMinutes: 10,
          maxMinutes: 60,
          canPause: true,
          requiresCompletion: false,
          isCompetitive: false,
          commitmentType: GameCommitmentType.flexible,
        ),
        GameActivity(
          id: 'mc_smp',
          gameId: 'minecraft',
          name: 'Multiplayer Server SMP',
          typicalDuration: 45,
          minMinutes: 20,
          maxMinutes: 90,
          canPause: false,
          requiresCompletion: false,
          isCompetitive: false,
          commitmentType: GameCommitmentType.flexible,
        ),
      ],
    ),
    GameProfile(
      id: 'gta_v',
      name: 'GTA V / FiveM',
      category: GameCategory.casual,
      iconName: 'gta',
      color: 0xFF4CAF50,
      activities: [
        GameActivity(
          id: 'gta_fivem',
          gameId: 'gta_v',
          name: 'FiveM Roleplay Session',
          typicalDuration: 60,
          minMinutes: 30,
          maxMinutes: 120,
          canPause: false,
          requiresCompletion: false,
          isCompetitive: false,
          commitmentType: GameCommitmentType.flexible,
        ),
        GameActivity(
          id: 'gta_heist',
          gameId: 'gta_v',
          name: 'Online Heist & Setup',
          typicalDuration: 35,
          minMinutes: 25,
          maxMinutes: 50,
          canPause: false,
          requiresCompletion: true,
          isCompetitive: true,
          commitmentType: GameCommitmentType.commitment,
        ),
        GameActivity(
          id: 'gta_story',
          gameId: 'gta_v',
          name: 'Story Mode / Free Roam',
          typicalDuration: 30,
          minMinutes: 15,
          maxMinutes: 60,
          canPause: true,
          requiresCompletion: false,
          isCompetitive: false,
          commitmentType: GameCommitmentType.flexible,
        ),
      ],
    ),
    GameProfile(
      id: 'terraria',
      name: 'Terraria',
      category: GameCategory.casual,
      iconName: 'terraria',
      color: 0xFF35A753,
      activities: [
        GameActivity(
          id: 'terra_adventure',
          gameId: 'terraria',
          name: 'Adventure & Building',
          typicalDuration: 30,
          minMinutes: 15,
          maxMinutes: 60,
          canPause: true,
          requiresCompletion: false,
          isCompetitive: false,
          commitmentType: GameCommitmentType.flexible,
        ),
        GameActivity(
          id: 'terra_boss',
          gameId: 'terraria',
          name: 'Boss Fight Progression',
          typicalDuration: 15,
          minMinutes: 10,
          maxMinutes: 25,
          canPause: true,
          requiresCompletion: false,
          isCompetitive: false,
          commitmentType: GameCommitmentType.flexible,
        ),
      ],
    ),
    GameProfile(
      id: 'stardew_valley',
      name: 'Stardew Valley',
      category: GameCategory.casual,
      iconName: 'stardew',
      color: 0xFFFF9800,
      activities: [
        GameActivity(
          id: 'stardew_day',
          gameId: 'stardew_valley',
          name: 'Daily In-Game Cycle (1 Day)',
          typicalDuration: 15,
          minMinutes: 12,
          maxMinutes: 16,
          canPause: true,
          requiresCompletion: false,
          isCompetitive: false,
          commitmentType: GameCommitmentType.flexible,
        ),
        GameActivity(
          id: 'stardew_multi',
          gameId: 'stardew_valley',
          name: 'Co-Op Farm Session',
          typicalDuration: 40,
          minMinutes: 20,
          maxMinutes: 60,
          canPause: false,
          requiresCompletion: false,
          isCompetitive: false,
          commitmentType: GameCommitmentType.flexible,
        ),
      ],
    ),
    GameProfile(
      id: 'roblox',
      name: 'Roblox',
      category: GameCategory.casual,
      iconName: 'roblox',
      color: 0xFFE53935,
      activities: [
        GameActivity(
          id: 'roblox_casual',
          gameId: 'roblox',
          name: 'Casual Obby / Roleplay / Chill',
          typicalDuration: 20,
          minMinutes: 10,
          maxMinutes: 45,
          canPause: true,
          requiresCompletion: false,
          isCompetitive: false,
          commitmentType: GameCommitmentType.flexible,
        ),
        GameActivity(
          id: 'roblox_match',
          gameId: 'roblox',
          name: 'Competitive Rivals / Bedwars Match',
          typicalDuration: 12,
          minMinutes: 8,
          maxMinutes: 18,
          canPause: false,
          requiresCompletion: true,
          isCompetitive: true,
          commitmentType: GameCommitmentType.shortSession,
        ),
      ],
    ),
    GameProfile(
      id: 'brawlstars',
      name: 'Brawl Stars',
      category: GameCategory.competitive,
      iconName: 'brawlstars',
      color: 0xFFFDC500,
      activities: [
        GameActivity(
          id: 'brawl_ranked',
          gameId: 'brawlstars',
          name: 'Ranked Match / Power League',
          typicalDuration: 6,
          minMinutes: 4,
          maxMinutes: 9,
          canPause: false,
          requiresCompletion: true,
          isCompetitive: true,
          commitmentType: GameCommitmentType.shortSession,
        ),
        GameActivity(
          id: 'brawl_showdown',
          gameId: 'brawlstars',
          name: 'Solo / Duo Showdown',
          typicalDuration: 4,
          minMinutes: 2,
          maxMinutes: 5,
          canPause: false,
          requiresCompletion: false,
          isCompetitive: false,
          commitmentType: GameCommitmentType.shortSession,
        ),
      ],
    ),
    GameProfile(
      id: 'clash_royale',
      name: 'Clash Royale',
      category: GameCategory.competitive,
      iconName: 'clash_royale',
      color: 0xFF1E88E5,
      activities: [
        GameActivity(
          id: 'cr_trophy',
          gameId: 'clash_royale',
          name: 'Trophy Road / Path of Legends',
          typicalDuration: 5,
          minMinutes: 3,
          maxMinutes: 6,
          canPause: false,
          requiresCompletion: true,
          isCompetitive: true,
          commitmentType: GameCommitmentType.shortSession,
        ),
        GameActivity(
          id: 'cr_party',
          gameId: 'clash_royale',
          name: '2v2 / Party Mode / Classic Challenge',
          typicalDuration: 4,
          minMinutes: 3,
          maxMinutes: 5,
          canPause: false,
          requiresCompletion: false,
          isCompetitive: false,
          commitmentType: GameCommitmentType.shortSession,
        ),
      ],
    ),
    GameProfile(
      id: 'clash_of_clans',
      name: 'Clash of Clans',
      category: GameCategory.casual,
      iconName: 'clash_of_clans',
      color: 0xFFFF9800,
      activities: [
        GameActivity(
          id: 'coc_multi',
          gameId: 'clash_of_clans',
          name: 'Multiplayer Attack & Farming',
          typicalDuration: 4,
          minMinutes: 3,
          maxMinutes: 5,
          canPause: false,
          requiresCompletion: false,
          isCompetitive: false,
          commitmentType: GameCommitmentType.shortSession,
        ),
        GameActivity(
          id: 'coc_war',
          gameId: 'clash_of_clans',
          name: 'Clan War Attack',
          typicalDuration: 4,
          minMinutes: 3,
          maxMinutes: 4,
          canPause: false,
          requiresCompletion: true,
          isCompetitive: true,
          commitmentType: GameCommitmentType.shortSession,
        ),
      ],
    ),
    GameProfile(
      id: 'genshin',
      name: 'Genshin Impact',
      category: GameCategory.casual,
      iconName: 'genshin',
      color: 0xFF48C5E2,
      activities: [
        GameActivity(
          id: 'gi_daily',
          gameId: 'genshin',
          name: 'Daily Commissions & Resin Domains',
          typicalDuration: 15,
          minMinutes: 10,
          maxMinutes: 20,
          canPause: true,
          requiresCompletion: false,
          isCompetitive: false,
          commitmentType: GameCommitmentType.flexible,
        ),
        GameActivity(
          id: 'gi_abyss',
          gameId: 'genshin',
          name: 'Spiral Abyss Floor 12',
          typicalDuration: 20,
          minMinutes: 15,
          maxMinutes: 30,
          canPause: true,
          requiresCompletion: false,
          isCompetitive: true,
          commitmentType: GameCommitmentType.flexible,
        ),
      ],
    ),
  ];
}
